MIN_NUMBER = 1
MAX_NUMBER = 100
MAX_PROGR = 5
PLUS_NUM = 1
MINUS_NUM = 3
WELCOME = 'Welcome to the Brain Games!\nMay I have your name? '
WRONG_ANSWER = 'is wrong answer ;(. Correct answer was'
EVEN = 'Answer "yes" if the number is even, otherwise answer "no".'
GCD = 'Find the greatest common divisor of given numbers.'
CALC = 'What is the result of the expression?'
PROGR = 'What number is missing in the progression?'
PRIME = 'Answer "yes" if given number is prime. Otherwise answer "no".'
